name: cfree
channels:
  - defaults
  - conda-forge
  - openbabel
dependencies:
  # Core dependencies
  - python==3.7.*
  - scikit-learn>=1
  - matplotlib>3
  - redis==5.0.3
  - redis-py==3.4.*
  - jupyterlab
  - pytest
  - flake8
  - pip

# Dependencies from the molecular design app
  - rdkit==2021.09.4
  - openbabel<3
  - pint==0.18.*
  - mongodb==4.*
  - psutil
  - tqdm

# Pip packages for all of them
  - pip:
      # Other
      - -e . 
      - parsl
      - mongoengine~=0.24
      - colmena

      # Autochem and its dependencies
      - libs/autochem
      - libs/autoio/autoio-base/
      - qcelemental
      - pyyaml
      - future
      - more_itertools
      - networkx
